tap "dracula/install"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
brew "gh"
brew "htop"
brew "prettyping"
brew "pure"
brew "the_silver_searcher"
brew "trash", link: true
brew "vercel-cli"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "dracula-macos-color-picker"
cask "font-fira-code"
cask "orbstack"
cask "raycast"